---
title: "525Final"
author: "Team 1 - Jillian Chapman, Amanda Hall, Tariq Mansaray, Jennifer Snyder, David Tannerr"
date: "10/8/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





##PROBLEM 3

Question - To better understand factors that influence the Balance variable.  Discuss the influential factors and the factors you choose to put in the model.

```{r}
library(dplyr)
library(ISLR)
library(alr4)
str(Credit)
head(Credit)
summary(Credit)
```

Problem Statement - What variables influence the amount of balance a client retains? The entire dataset will be consider when designating a model.

```{r}
Credit2=Credit%>% filter(Balance>0)
summary(Credit2)
plot(Credit2)
```

```{r}
CRMod1<-lm(Balance~., data=Credit2)
summary(CRMod1)
par(mfrow=c(2,2))
plot(CRMod1)
anova(CRMod1)
```
```{r}
CRMod2<-lm(Balance~Income+Limit+Rating+Cards+Age+Education+Gender+Student, data=Credit2)
summary(CRMod2)
par(mfrow=c(2,2))
plot(CRMod2)
anova(CRMod2)
anova(CRMod2,CRMod1)
```

```{r}
residualPlot(CRMod2)
ncvTest(CRMod2)
boxCox(CRMod2)
attach(Credit2)
summary(powerTransform(cbind(Balance,Income,Limit,Rating,Cards,Age,Education,Gender,Student)))
detach(Credit2)
```

```{r}
CRMod3<-lm(sqrt(Balance)~Income+sqrt(Limit)+sqrt(Rating)+sqrt(Cards)+Age^2+Student, data=Credit)
summary(CRMod3)
par(mfrow=c(2,2))
plot(CRMod3)
anova(CRMod3)
```